### ISSUE TITLE
Add a settings to override the hard coded limit of 5 containers

### ISSUE THREAD

**Issue by SiberianCMS** [obstrom/packer-app-api#2]
The code below prevents any computation where there is more than 5 containers to be filled, a settings would be appreciated!

https://github.com/obstrom/packer-app-api/blob/cb2a7b8cd788d4becd996ca2aaa1785f5632191c/src/main/java/com/obstrom/packerservice/core/packer/Packager.java#L67

Thanks

**Comment by obstrom** [comment]
Thanks for the feedback, and good suggestion!

However I'm not currently maintaining this repo with any updates or new features as this was only ever intended as a __demo project__ and part of a school project that had to be open source. I'll be sure make this fact more obvious in the README.

Anyone interested is more then welcome to fork this repo and implement any changes they'd like in their own fork.

If you want to implement this yourself as another environment variable/application setting then:
- Load the variable into the Spring app via `application.yml` and the `PackerProperties.java`-class.
- Update the `Packager.java`-class constructor(s) to take another parameter for this.
- In the `PackingService.java`-class, in the constructor, add the variable from `PackerProperties`:

````
new Packager(_, _, _, this.packerProperties.getFooBar());
````

**Comment by SiberianCMS** [comment]
Thanks for the feedback anyway, we will fork it so!
